let x = -10.7;
let res = Math.floor(x);
console.log(res);
res = Math.trunc(x);
console.log(res);
res = Math.round(x);
console.log(res);
res = Math.random();
console.log(res);
console.log(Math.PI);
res = Math.pow(3, 4);
console.log(res);
res = Math.min(7, 2, 9, 11, 4);
console.log(res);